DoAn_63134144/Controllers/BookcasualController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn_63134144.Models;

namespace DoAn_63134144.Controllers
{
    public class BookcasualController : Controller
    {
        private DOANQLEntities14 db = new DOANQLEntities14();

        // GET: Bookcasual
        public string getID()
        {
            // Lấy Id_user cao nhất từ cơ sở dữ liệu
            var lastId = db.BOOKS.ToList().Select(n => n.Id_book).Max();

            int ma = int.Parse(lastId.Substring(2)) + 1;

            var newId = "BO" + ma.ToString("D7"); // Định dạng lại chuỗi Id_user mới

            return newId;
        }
        public string getIDJob()
        {
            // Lấy Id_user cao nhất từ cơ sở dữ liệu
            var lastId = db.JOBS.ToList().Select(n => n.Id_job).Max();
            int ma;
            if (lastId != null)
            {
                ma = int.Parse(lastId.Substring(2)) + 1;
            }
            else ma = 1;
            

            var newId = "JO" + ma.ToString("D11"); // Định dạng lại chuỗi Id_user mới

            return newId;
        }
        public bool Security(string value)
        {
            string kind = Session["Type"] != null ? Session["Type"].ToString() : null;
            if(value != kind) return false;
            return true;
        }
        public ActionResult Index()
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            DateTime currentDate = DateTime.Now.Date;
            string id = Session["Id"].ToString();
            var book = db.BOOKS.Where(b => b.Id_hr == id && b.Ngay >= currentDate).ToList();
            return View(book);
        }

        // GET: Bookcasual/Details/5

        // GET: Bookcasual/Create
        public ActionResult Create()
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            return View();
        }

        // POST: Bookcasual/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_hr,Ngay,Tstart,Tend,Price,Support,Location,Note")] BOOK bOOK)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            if (ModelState.IsValid)
            {
                bOOK.Id_book= getID();
                db.BOOKS.Add(bOOK);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bOOK);
        }

        // GET: Bookcasual/Edit/5
        public ActionResult Edit(string id)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOK bOOK = db.BOOKS.Find(id);
            if (bOOK == null)
            {
                return HttpNotFound();
            }
            return View(bOOK);
        }

        // POST: Bookcasual/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_book,Id_hr,Ngay,Tstart,Tend,Price,Support,Location,Note")] BOOK bOOK)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            if (ModelState.IsValid)
            {
                db.Entry(bOOK).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bOOK);
        }
        public ActionResult DeleteJob(string id)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            string type = Session["Type"].ToString();
            JOB jOB = db.JOBS.Find(id);
            db.JOBS.Remove(jOB);
            db.SaveChanges();
            return RedirectToAction("JobDangKy");
        }

        // POST: Job/Delete/5

        public ActionResult DeleteByHr(string id)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            JOB jOB = db.JOBS.Find(id);

            ///gửi thông tin hủy ca về casual
            ///
            /// 
            System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage();
            mail.From = new System.Net.Mail.MailAddress("hung.nbn.63cntt@ntu.edu.vn");
            mail.To.Add(jOB.USER.Email);
            mail.Subject = "Hủy ca làm";
            mail.Body = "hủy ca ngày" + jOB.Ngay + ", ca làm :" + jOB.Tstart + " đến :" + jOB.Tend + " ở :" + jOB.HR.Ten_KS;
   
            mail.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential("hung.nbn.63cntt@ntu.edu.vn", "225774478");
            smtp.EnableSsl = true;
            smtp.Send(mail);

            /// 
            ///
            db.JOBS.Remove(jOB);
            db.SaveChanges();
            return RedirectToAction("Danhsach");
        }

        // POST: Job/Delete/5

        // GET: Bookcasual/Delete/5
        public ActionResult Delete(string id)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOK bOOK = db.BOOKS.Find(id);
            if (bOOK == null)
            {
                return HttpNotFound();
            }
            return View(bOOK);
        }

        // POST: Bookcasual/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (!Security("2")) return RedirectToAction("login", "Login");
            BOOK bOOK = db.BOOKS.Find(id);
            db.BOOKS.Remove(bOOK);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //// đăng ký
        ////
        ///
        public ActionResult Dangky()
        {
            if (!Security("1")) return RedirectToAction("login", "Login");
            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewBag.SuccessMessage = TempData["SuccessMessage"].ToString();
            }
            if (TempData.ContainsKey("ErrorMessage"))
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            }
            DateTime currentDate = DateTime.Now.Date;
            var book = db.BOOKS.Where(b => b.Ngay >= currentDate).OrderBy(b => b.Ngay).ToList();
            return View(book);
        }
        public ActionResult DangkyAD()
        {
            if (!Security("0")) return RedirectToAction("login", "Login");
            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewBag.SuccessMessage = TempData["SuccessMessage"].ToString();
            }
            if (TempData.ContainsKey("ErrorMessage"))
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            }
            DateTime currentDate = DateTime.Now.Date;
            var book = db.BOOKS.Where(b => b.Ngay >= currentDate).OrderBy(b => b.Ngay).ToList();
            return View(book);
        }
        public HttpRequestBase GetRequest()
        {
            return Request;
        }



        public ActionResult CreateJob([Bind(Include = "Id_job,Id_hr,Ngay,Tstart,Tend,Price,Support,Sta,Pay,Id_user,Note,Id_change,Status_change,Location")] JOB jOB,
                               string Id_hr, string Ngay, string Tstart, string Tend, string Price, string Support, string Note,string Location)
        {
            if (!Security("1")) return RedirectToAction("login", "Login");
            var userID = Session["Id"].ToString();
            TimeSpan startTime = TimeSpan.Parse(Tstart);
            TimeSpan endTime = TimeSpan.Parse(Tend);
            DateTime ngay = DateTime.Parse(Ngay);
            var check = db.JOBS.Where(c => c.Ngay== ngay && c.Id_user == userID && c.Location==Location && c.Id_hr == Id_hr && c.Tstart == startTime && c.Tend == endTime);
            if (!check.Any())
            {
                jOB.Id_job = getIDJob();
                jOB.Id_hr = Id_hr;
                jOB.Ngay = DateTime.Parse(Ngay);
                jOB.Tstart = TimeSpan.Parse(Tstart);
                jOB.Tend = TimeSpan.Parse(Tend);
                jOB.Price = Decimal.Parse(Price);
                jOB.Support = Decimal.Parse(Support);
                jOB.Location = Location;
                jOB.Sta = "0";
                jOB.Pay = "0";
                jOB.Id_user = userID;
                jOB.Note = Note;
                jOB.Id_change = "";
                jOB.Status_change = "";

                db.JOBS.Add(jOB);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Đăng ký thành công.";
                return RedirectToAction("Dangky");
            }

            TempData["ErrorMessage"] = "Đăng ký thất bại.";
            return RedirectToAction("Dangky");
        }

        public ActionResult JobDangKy()
        {
            if (!Security("1")) return RedirectToAction("login", "Login");
            DateTime currentDate = DateTime.Now.Date;
            string id = Session["Id"].ToString();

DoAn_63134144/Views/Bookcasual/ChangeTime.cshtml
@{
    ViewBag.Title = "ChangeTime";
    Layout = "~/Views/Shared/_layoutControl.cshtml";
}

<div class="changepassword">
    <div class="row justify-content-center mt-2 mt-md-5">
        <div class="col-md-6">
            <div class="border p-4">
                @using (Html.BeginForm("ConfirmChangeTime", "Bookcasual", FormMethod.Post))
                {
                    <div class="form-group">
                        <label for="id"></label>
                        <input type="text" class="form-control" id="id" name="id" required hidden value="@ViewBag.id">
                    </div>

                    <div class="form-group">
                        <label for="newStart">Nhập lại giờ vào:</label>
                        <input type="time" class="form-control" id="newStart" name="newStart" required>
                    </div>

                    <div class="form-group">
                        <label for="newEnd">Nhập lại giờ ra</label>
                        <input type="time" class="form-control" id="newEnd" name="newEnd" required>
                    </div>

                    <button type="submit" id="submitButton" class="btn btn-primary">Submit</button>
                }
            </div>
        </div>
    </div>
</div>

DoAn_63134144/Views/Bookcasual/ChuyenCa.cshtml
@{
    ViewBag.Title = "ChuyenCa";
    Layout = "~/Views/Shared/_layoutAdmin.cshtml";
}

<div class="chuyenca">
    <div class="row justify-content-center mt-2 mt-md-5">
        <div class="col-md-6">
            <div class="border p-4">
                @using (Html.BeginForm("ConFirmChuyenCa", "Bookcasual", FormMethod.Post))
                {
                    <div class="form-group">
                        <label for="Id_job"></label>
                        <input type="text" class="form-control" id="Id_job" name="Id_job" value="@ViewBag.Id_job" required hidden>
                    </div>
                    <div class="form-group">
                        <label for="Id_change">Chuyển cho ID</label>
                        <input type="text" class="form-control" id="Id_change" name="Id_change" placeholder="Nếu không nhập thì chuyển lên trang nhượng ca">
                    </div>
                    <button type="submit" id="submitButton" class="btn btn-primary">Submit</button>
                }
            </div>
        </div>
    </div>
</div>

DoAn_63134144/Views/Bookcasual/ConfirmLuong.cshtml
@{
    ViewBag.Title = "ConfirmLuong";
    Layout = "~/Views/Shared/_layoutControl.cshtml";
}

@model IEnumerable<DoAn_63134144.Models.JOB>

<style>
    .link-black {
        color: black;
    }

        .link-black:hover {
            color: blue;
        }

    .table {
        width: 100%;
        table-layout: fixed;
        border: 1px solid black;
    }

    @@media only screen and (max-width:767px) {
        .table th,
        .table td {
            font-size: 10px;
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }

    @@media only screen and (min-width:768px) {
        .table th,
        .table td {
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }
</style>
<table class="table">
    <tr class="col-12">
        <th class="col-1">Khách sạn</th>
        <th class="col-1">Ngày</th>
        <th class="col-1">Thời gian</th>
        <th class="col-1">Lương</th>
        <th class="col-1">Hỗ trợ</th>
        <th class="col-3 col-md-2">Họ tên</th>
    </tr>

    @foreach (var item in Model)
    {
        string formattedPrice = (item.Price / 1000).ToString() + "k";
        string formattedSupport = (item.Support / 1000).ToString() + "k";
        <tr>
            <td>@item.HR.Short_name</td>
            <td>@(((DateTime)item.Ngay).ToString("dd/MM"))</td>
            <td>@item.Tstart - @item.Tend</td>
            <td>@formattedPrice</td>
            <td>@formattedSupport</td>
            <td>@item.USER.Ho @item.USER.Ten_lot @item.USER.Ten</td>
        </tr>
    }

</table>

DoAn_63134144/Views/Bookcasual/Create.cshtml
@model DoAn_63134144.Models.BOOK  

@{  
    ViewBag.Title = "Create";  
    Layout = "~/Views/Shared/_layoutHR.cshtml";  
}  

@using (Html.BeginForm())   
{  
    @Html.AntiForgeryToken()  
<div>  
    <div class="row justify-content-center">  
        <div class="col-md-8">  
            <div class="card">  
                <div class="card-body">  
                    <h4 class="card-title">Thông tin book casual</h4>  
                    <hr />  
                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Id_hr, "Id_hr", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <input type="text" id="Id_hr" name="Id_hr" class="form-control" readonly value="@Session["Id"]" />  
                            @Html.ValidationMessageFor(model => model.Id_hr, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Ngay, "Ngày", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <input type="date" id="Ngay" name="Ngay" class="form-control" required oninput="checkFields()" />  
                            @Html.ValidationMessageFor(model => model.Ngay, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Tstart, "Thời gian bắt đầu", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <input type="time" id="Tstart" name="Tstart" class="form-control" required oninput="checkFields()" />  
                            @Html.ValidationMessageFor(model => model.Tstart, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Tend, "Thời gian kết thúc", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <input type="time" id="Tend" name="Tend" class="form-control" required oninput="checkFields()" />  
                            @Html.ValidationMessageFor(model => model.Tend, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Price, "Lương", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <input type="number" id="Price" name="Price" class="form-control" required oninput="checkFields()" step="1000" />  
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Support, "Hỗ trợ thêm", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <input type="number" id="Support" name="Support" class="form-control" required oninput="checkFields()" step="1000" />  
                            @Html.ValidationMessageFor(model => model.Support, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Location, "Vị trí làm việc", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <select id="Location" name="Location" class="form-control" required onchange="checkFields()">  
                                <option value="">-- Chọn vị trí --</option>  
                                <option value="FB">FB</option>  
                                <option value="KIT">KIT</option>  
                                <option value="HK">HK</option>  
                                <option value="RUNNER">RUNNER</option>  
                                <option value="HAUCAN">HẬU CẦN</option>  
                                <option value="SETUP">SET UP</option>  
                            </select>  
                            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        @Html.LabelFor(model => model.Note, "Ghi chú", htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })  
                        <div class="col-md-6">  
                            <textarea id="Note" name="Note" class="form-control" style="height: 200px;"></textarea>  
                            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })  
                        </div>  
                    </div>  

                    <div class="form-group row">  
                        <div class="col-md-6 offset-md-4">  
                            <input type="submit" value="Tuyển công nhật" class="btn btn-primary" disabled />  
                        </div>  
                    </div>  
                </div>  
            </div>  
        </div>  
    </div>  
</div>   
}  

<script>
    function checkFields() {
        var inputs = document.querySelectorAll('.form-control[required]');
        var isAllFilled = true;

        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].value === '') {
                inputs[i].style.border = '2px solid red'; // Đặt viền đỏ nếu ô trống
                isAllFilled = false;
            } else {
                inputs[i].style.border = ''; // Đặt lại viền bình thường nếu đã nhập
            }
        }

        // Kiểm tra các trường Lương và Hỗ trợ thêm
        var priceInput = document.getElementById('Price');
        var supportInput = document.getElementById('Support');
        var warning = false;

        // Hàm kiểm tra ký tự không hợp lệ
        function hasInvalidChars(value) {
            return /\s/.test(value) || /[^\w\s]/.test(value); // Ký tự đặc biệt và khoảng trắng ở đầu
        }

        if (hasInvalidChars(priceInput.value)) {
            priceInput.style.border = '2px solid red'; // Đặt viền đỏ nếu có ký tự không hợp lệ
            warning = true;
        } else {
            priceInput.style.border = ''; // Đặt viền bình thường nếu không có ký tự không hợp lệ
        }

        if (hasInvalidChars(supportInput.value)) {
            supportInput.style.border = '2px solid red'; // Đặt viền đỏ nếu có ký tự không hợp lệ
            warning = true;
        } else {
            supportInput.style.border = ''; // Đặt viền bình thường nếu không có ký tự không hợp lệ
        }

        var createButton = document.querySelector('.btn.btn-primary');
        // Kích hoạt nút nếu tất cả các trường đều đã được điền và không có cảnh báo
        createButton.disabled = !isAllFilled || warning;
    }
</script>

DoAn_63134144/Views/Bookcasual/Dangky.cshtml
@model IEnumerable<DoAn_63134144.Models.BOOK>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layoutUser.cshtml";
}
<style>
    .link-black {
        color: black;
    }
    .link-black:hover{
        color:blue;
    }
    .table {
        width: 100%;
        table-layout: fixed;
        border: 1px solid black;
    }

    @@media only screen and (max-width:767px) {
        .table th,
        .table td {
            font-size: 10px;
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }

    @@media only screen and (min-width:768px) {
        .table th,
        .table td {
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }
</style>
<h2>Danh sách các công việc có thể đăng ký</h2>
@ViewBag.SuccessMessage@ViewBag.ErrorMessage
<table class="table">
    <tr>
        <td class="col-1">Nơi làm việc</td>
        <td class="col-1">Ngày</td>
        <td class="col-1">thời gian</td>
        <td class="col-1">Lương (/h)</td>
        <td class="col-1">Hỗ trợ</td>
        <td class="col-1">Vị trí</td>
        <td class="col-2">Lưu ý</td>
        <td class="col-1">Đăng ký</td>
    </tr>
    @foreach (var item in Model)
    {
        string formattedPrice = (item.Price / 1000).ToString() + "k";
        string formattedSupport = (item.Support / 1000).ToString() + "k";
        <tr>
            <td>@item.HR.Short_name</td>
            <td>@(((DateTime)item.Ngay).ToString("dd/MM"))</td>
            <td>thời gian</td>
            <td>@formattedPrice</td>
            <td>@formattedSupport</td>
            <td>@item.Location</td>
            <td>@item.Note</td>
            <td>
                @Html.ActionLink("Đăng ký", "CreateJob", new
                    {
                        Id_hr = item.Id_hr,
                        Ngay = item.Ngay,
                        Tstart = item.Tstart,
                        Tend = item.Tend,
                        Price = item.Price,
                        Support = item.Support,
                        Location = item.Location,
                        Note = item.Note
                    }, new { @class = "link-black" })
            </td>
        </tr>
    }
</table>

DoAn_63134144/Views/Bookcasual/DangkyAD.cshtml
@model IEnumerable<DoAn_63134144.Models.BOOK>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layoutControl.cshtml";
}
<style>
    .link-black {
        color: black;
    }

        .link-black:hover {
            color: blue;
        }

    .table {
        width: 100%;
        table-layout: fixed;
        border: 1px solid black;
    }

    @@media only screen and (max-width:767px) {
        .table th,
        .table td {
            font-size: 10px;
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }

    @@media only screen and (min-width:768px) {
        .table th,
        .table td {
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }
</style>
<h2>Danh sách các công việc</h2>
<table class="table">
    <tr>
        <td class="col-1">Nơi làm việc</td>
        <td class="col-1">Ngày</td>
        <td class="col-1">thời gian</td>
        <td class="col-1">Lương (/h)</td>
        <td class="col-1">Hỗ trợ</td>
        <td class="col-1">Vị trí</td>
        <td class="col-2">Lưu ý</td>
    </tr>
    @foreach (var item in Model)
    {
        string formattedPrice = (item.Price / 1000).ToString() + "k";
        string formattedSupport = (item.Support / 1000).ToString() + "k";
        <tr>
            <td>@item.HR.Short_name</td>
            <td>@(((DateTime)item.Ngay).ToString("dd/MM"))</td>
            <td>thời gian</td>
            <td>@formattedPrice</td>
            <td>@formattedSupport</td>
            <td>@item.Location</td>
            <td>@item.Note</td>
        </tr>
    }
</table>

DoAn_63134144/Views/Bookcasual/Danhsach.cshtml
@{
    ViewBag.Title = "Danhsach";
    Layout = "~/Views/Shared/_layoutHR.cshtml";
}

@model IEnumerable<DoAn_63134144.Models.JOB>

<style>
    .link-black {
        color: black;
    }

    .link-black:hover {
        color: blue;
    }
    .table {
        width: 100%;
        table-layout: fixed;
        border: 1px solid black;
    }

    @@media only screen and (max-width:767px) {
        .table th,
        .table td {
            font-size: 10px;
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }

    @@media only screen and (min-width:768px) {
        .table th,
        .table td {
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }
</style>
<table class="table">
    <tr class="col-12">

        <th class="col-1">Ngày</th>
        <th class="col-1">Thời gian</th>
        <th class="col-1">Lương</th>
        <th class="col-1">Hỗ trợ</th>
        <th class="col-3 col-md-2">Họ tên</th>
        <th class="col-2">Lưu ý</th>
        <th class="col-1"></th>
    </tr>

    @foreach (var item in Model)
    {
        string formattedPrice = (item.Price / 1000).ToString() + "k";
        string formattedSupport = (item.Support / 1000).ToString() + "k";
        <tr>

            <td>@(((DateTime)item.Ngay).ToString("dd/MM"))</td>
            <td>@item.Tstart - @item.Tend</td>
            <td>@formattedPrice</td>
            <td>@formattedSupport</td>
            <td>@item.USER.Ho @item.USER.Ten_lot @item.USER.Ten</td>
            <td>@item.Note</td>
            <td>@Html.ActionLink("Xóa", "DeleteByHr", new { id = item.Id_job }, new { @class = "link-black" }) || @Html.ActionLink("Sửa thời gian", "ChangeTime", new { id = item.Id_job }, new { @class = "link-black" })</td>
        </tr>
    }

</table>

DoAn_63134144/Views/Bookcasual/JobDangKy.cshtml
@{
    ViewBag.Title = "JobDangKy";
    Layout = "~/Views/Shared/_layoutUser.cshtml";
}

@model IEnumerable<DoAn_63134144.Models.JOB>

<style>
    .link-black {
        color: black;
    }

    .link-black:hover {
        color: blue;
    }
    .table {
        width: 100%;
        table-layout: fixed;
        border: 1px solid black;
    }

    @@media only screen and (max-width:767px) {
        .table th,
        .table td {
            font-size: 10px;
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }

    @@media only screen and (min-width:768px) {
        .table th,
        .table td {
            border: 1px solid red;
            padding: 0px;
            text-align: center;
        }
    }
</style>
<h3>DANH SÁCH CÁC CÔNG VIỆC ĐANG ĐĂNG KÝ, CẦN ĐƯỢC HR XÁC NHẬN ĐỂ ĐI LÀM</h3>
<table class="table">
    <tr>
        <td class="col-2">Nơi làm việc</td>
        <td class="col-1">Ngày</td>
        <td class="col-1">thời gian</td>
        <td class="col-1">Lương (/h)</td>
        <td class="col-1">Hỗ trợ</td>
        <td class="col-1">Vị trí</td>
        <td class="col-2">Lưu ý</td>
        <td class="col-1">Hủy đăng ký</td>
    </tr>
    @foreach (var item in Model)
    {
        string formattedPrice = (item.Price / 1000).ToString() + "k";
        string formattedSupport = (item.Support / 1000).ToString() + "k";
        string sex = "";
        DateTime? Nsinh = item.USER.Ngsinh;
        int tuoi;
        TimeSpan? timeSpan = DateTime.Now - Nsinh;
        tuoi = (int)(timeSpan.Value.TotalDays / 365.25);
        if (item.USER.Gtinh == "0") { sex = "Nam"; }
        else { sex = "Nữ"; }
        <tr>
            <td>@item.HR.Short_name</td>
            <td>@(((DateTime)item.Ngay).ToString("dd/MM"))</td>
            <td>thời gian</td>
            <td>@formattedPrice</td>
            <td>@formattedSupport</td>
            <td>@item.Location</td>
            <td>@item.Note</td>
            <td>@Html.ActionLink("Xóa đăng ký", "DeleteJob", new { id = item.Id_job }, new { @class = "link-black" })</td>
        </tr>
    }
</table>